### ISSUE TITLE
Crash on macOS while finding configuration file

### ISSUE THREAD

**Issue by bgshacklett** [bgshacklett/samlogin#9]
index.js currently tries to find the configuration file in multiple places, starting with LocalAppData. This is, obviously, not available on macOS and it causes a crash due to a null reference error.

Example error:
samlogin (node:86066) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined at validateString (internal/validators.js:125:11) at Object.resolve (path.js:1080:7) at el (/Users/bxl93/homebrew/lib/node_modules/samlogin/node_modules/locate-path/index.js:11:49) (node:86066) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4) (node:86066) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by bgshacklett** [comment]
Probable cause: https://github.com/bgshacklett/samlogin/blob/master/index.js#L105-L110 and https://github.com/bgshacklett/samlogin/blob/master/index.js#L125
